version: '3.7'

services:
  web-fii:
    image: nginx:latest
    container_name: web-nginx-fii
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php-fii
    networks:
      - fiis
  php-fii:
    build: .
    # image: php:7.4-fpm
    container_name: php-fii
    volumes:
    - ./:/www
    ports:
      - "9000:9000"
    networks:
      - fiis
      
networks:
  fiis:
    driver: bridge

  # cosmos-back-end:
  #   image: ambientum/php:7.4-nginx
  #   container_name: cosmos-back-end
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - .:/var/www/app

  # cosmos-back-end-mysql:
  #   image: mysql:5.7
  #   command: mysqld --sql_mode=""
  #   container_name: cosmos-back-end-mysql
  #   volumes:
  #     - ./storage/docker/mysql:/var/lib/mysql
  #   ports:
  #     - 3308:3306
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: farmarcas
  #     MYSQL_DATABASE: farmarcas
  #     MYSQL_USER: farmarcas
  #     MYSQL_PASSWORD: farmarcas
      # COPY DUMP FILE INTO MYSQL CONTAINER: docker cp "path/to/dump.sql" cosmos-back-end-mysql:/dump.sql
      # IMPORT MYSQL DUMP: docker exec -i cosmos-back-end-mysql mysql -h 127.0.0.1 -u root -pfarmarcas farmarcas < dump.sql
